//* Lista de todas las divisas que estaran disponibles para el conversor
// Formado por el código y el nombre en castellano
const listaDivisas = {
  EUR: "Euro",
  USD: "Dólar estadounidense",
  GBP: "Libra esterlina",
  JPY: "Yen japonés",
  AUD: "Dólar australiano",
  CAD: "Dólar canadiense",
  CHF: "Franco suizo",
  CNY: "Yuan chino",
  SEK: "Corona sueca",
  NZD: "Dólar neozelandés",
  MXN: "Peso mexicano",
  SGD: "Dólar de Singapur",
  HKD: "Dólar de Hong Kong",
  NOK: "Corona noruega",
  KRW: "Won surcoreano",
  TRY: "Lira turca",
  RUB: "Rublo ruso",
  INR: "Rupia india",
  BRL: "Real brasileño",
  ZAR: "Rand sudafricano",
  DKK: "Corona danesa",
  PLN: "Zloty polaco",
  TWD: "Nuevo dólar taiwanés",
  THB: "Baht tailandés",
  MYR: "Ringgit malayo",
  HUF: "Florín húngaro",
  CZK: "Corona checa",
  ILS: "Nuevo séquel israelí",
  CLP: "Peso chileno",
  PHP: "Peso filipino",
  AED: "Dírham de los Emiratos Árabes Unidos",
  COP: "Peso colombiano",
  SAR: "Riyal saudí",
  RON: "Leu rumano",
  IDR: "Rupia indonesia",
  PKR: "Rupia pakistaní",
  EGP: "Libra egipcia",
  HRK: "Kuna croata",
  BGN: "Lev búlgaro",
  ARS: "Peso argentino",
  ISK: "Corona islandesa",
  BHD: "Dinar bareiní",
  KWD: "Dinar kuwaití",
  OMR: "Rial omaní",
  QAR: "Rial catarí",
  JOD: "Dinar jordano",
  LYD: "Dinar libio",
  TND: "Dinar tunecino",
  BWP: "Pula botsuano",
  LKR: "Rupia de Sri Lanka",
  MUR: "Rupia mauriciana",
  KES: "Chelín keniano",
  UGX: "Chelín ugandés",
  TZS: "Chelín tanzano",
  GHS: "Cedi ghanés",
  NGN: "Naira nigeriano",
  AWG: "Florín arubeño",
  BSD: "Dólar bahameño",
  BZD: "Dólar beliceño",
  BMD: "Dólar bermudeño",
  FJD: "Dólar fiyiano",
  GYD: "Dólar guyanés",
  HTG: "Gourde haitiano",
  HNL: "Lempira hondureño",
  JMD: "Dólar jamaicano",
  SBD: "Dólar de las Islas Salomón",
  TTD: "Dólar de Trinidad y Tobago",
  VND: "Dong vietnamita",
  KZT: "Tenge kazajo",
  UZS: "Som uzbeko",
  GEL: "Lari georgiano",
  MDL: "Leu moldavo",
  MNT: "Tugrik mongol",
  ZWL: "Dólar zimbabuense",
  KPW: "Won norcoreano",
  MWK: "Kwacha malauí",
  CUP: "Peso cubano",
  MGA: "Ariary malgache",
  LAK: "Kip laosiano",
  MZN: "Metical mozambiqueño",
  YER: "Rial yemení",
  SOS: "Chelín somalí",
  SYP: "Libra siria",
  DZD: "Dinar argelino",
  AFN: "Afgani afgano",
  KHR: "Riel camboyano",
  BTN: "Ngultrum butanés",
  LTL: "Litas lituano",
  LVL: "Lats letón",
  ALL: "Lek albanés",
  NPR: "Rupia nepalí",
  BDT: "Taka bangladesí",
  ZMW: "Kwacha zambiano",
  SDG: "Libra sudanesa",
  RSD: "Dinar serbio",
  MKD: "Denar macedonio",
  BAM: "Marco convertible bosnio",
  BBD: "Dólar de Barbados",
  BND: "Dólar de Brunéi",
  MMK: "Kyat birmano",
};
