//* Lista de todas las divisas que estaran disponibles para el conversor
// Formado por el código y el nombre en castellano
const listaDivisas = {
  EUR: "Euro",
  USD: "Dólar estadounidense",
  GBP: "Libra esterlina",
  JPY: "Yen japonés",
  AUD: "Dólar australiano",
  CAD: "Dólar canadiense",
  CHF: "Franco suizo",
  CNY: "Yuan chino",
  SEK: "Corona sueca",
  NZD: "Dólar neozelandés",
  MXN: "Peso mexicano",
  SGD: "Dólar de Singapur",
  HKD: "Dólar de Hong Kong",
  NOK: "Corona noruega",
  KRW: "Won surcoreano",
  TRY: "Lira turca",
  INR: "Rupia india",
  BRL: "Real brasileño",
  ZAR: "Rand sudafricano",
  DKK: "Corona danesa",
  PLN: "Zloty polaco",
  THB: "Baht tailandés",
  MYR: "Ringgit malayo",
  HUF: "Florín húngaro",
  CZK: "Corona checa",
  ILS: "Nuevo séquel israelí",
  PHP: "Peso filipino",
  RON: "Leu rumano",
  IDR: "Rupia indonesia",
  BGN: "Lev búlgaro",
  ISK: "Corona islandesa",
};

